package com.valentsolutions.xml.statepattern.providedstates;

/**
 * An enumeration of error codes that can be generated by any of the
 * ProvidedStates.
 */
public class StateError
{
    /**
     * Used when the end of the document is reached when there are still open
     * elements.
     */
	public static final StateError END_OF_DOCUMENT = new StateError();

    /**
     * Used when an element is encountered that can not be handled.
     */
    public static final StateError ILLEGAL_ELEMENT = new StateError();
    
    /**
     * Used when there is a problem calling a method from a GenericValueState.
     */
    public static final StateError METHOD = new StateError();
    
    /**
     * Used when a value does not match the expected format.
     */
    public static final StateError ILLEGAL_VALUE = new StateError();
	
    /**
     * An empty constructor for the enumeration.
     */
	private StateError()
	{
	}
}
